networks:
  kong-air-net:      # Custom bridge network for isolated Kong and Postgres communication
    driver: bridge

services:

  flights.kongair:
    image: 'ghcr.io/jeromeguillaume/kongair-flights:latest'
    container_name: flights.kongair
    restart: on-failure
    platform: linux/amd64
    networks:
      - kong-air-net

  routes.kongair:
    image: 'ghcr.io/jeromeguillaume/kongair-routes:latest'
    container_name: routes.kongair
    restart: on-failure
    platform: linux/amd64
    networks:
      - kong-air-net

  bookings.kongair:
    image: 'ghcr.io/jeromeguillaume/kongair-bookings:latest'
    container_name: bookings.kongair
    restart: on-failure
    platform: linux/amd64
    networks:
      - kong-air-net
    environment:
      FLIGHT_SVC_ENDPOINT: http://flights.kongair:8079    

  customer.kongair:
    image: 'ghcr.io/jeromeguillaume/kongair-customer:latest'
    container_name: customer.kongair
    restart: on-failure
    platform: linux/amd64
    networks:
      - kong-air-net

  experience.kongair:
    image: 'ghcr.io/jeromeguillaume/kongair-experience:latest'
    container_name: experience.kongair
    restart: on-failure
    platform: linux/amd64
    networks:
      - kong-air-net

  kong-air-dp:
    image: 'kong/kong-gateway:3.11.0.2'  # Main Kong Gateway Control Plane (default to latest version)
    container_name: kong-air-dp
    restart: on-failure
    networks:
      - kong-air-net
    environment:
      KONG_ROLE: data_plane
      KONG_DATABASE: off
      KONG_VITALS: off
      KONG_CLUSTER_MTLS: pki
      KONG_PROXY_LISTEN: 0.0.0.0:9000, 0.0.0.0:9443 ssl
      KONG_CLUSTER_CONTROL_PLANE: 77f85689e2.eu.cp.konghq.com:443
      KONG_CLUSTER_SERVER_NAME: 77f85689e2.eu.cp.konghq.com
      KONG_CLUSTER_TELEMETRY_ENDPOINT: 77f85689e2.eu.tp.konghq.com:443
      KONG_CLUSTER_TELEMETRY_SERVER_NAME: 77f85689e2.eu.tp.konghq.com
      KONG_LOG_LEVEL: notice
      KONG_CLUSTER_CERT: |
        -----BEGIN CERTIFICATE-----
        MIICFjCCAbygAwIBAgIBATAKBggqhkjOPQQDBDA8MTowCQYDVQQGEwJFVTAtBgNV
        BAMeJgBrAG8AbgBuAGUAYwB0AC0ASwBvAG4AZwBBAGkAcgAtAFAAUgBEMB4XDTI1
        MTAwMjA4MDA0N1oXDTM1MTAwMjA4MDA0N1owPDE6MAkGA1UEBhMCRVUwLQYDVQQD
        HiYAawBvAG4AbgBlAGMAdAAtAEsAbwBuAGcAQQBpAHIALQBQAFIARDBZMBMGByqG
        SM49AgEGCCqGSM49AwEHA0IABJSeI8JfShMjuiEMtr1+ml+Eoiz1reIhJ9BYDwzM
        2QmvrfdVpMSWleORB+5+nN+YX8vdbJzhJ2GbwWUBiKWu9Mqjga4wgaswDAYDVR0T
        AQH/BAIwADALBgNVHQ8EBAMCAAYwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUF
        BwMCMBcGCSsGAQQBgjcUAgQKDAhjZXJ0VHlwZTAjBgkrBgEEAYI3FQIEFgQUAQEB
        AQEBAQEBAQEBAQEBAQEBAQEwHAYJKwYBBAGCNxUHBA8wDQYFKQEBAQECAQoCARQw
        EwYJKwYBBAGCNxUBBAYCBAAUAAowCgYIKoZIzj0EAwQDSAAwRQIhAPP4NAH4gA3+
        KqzhQgY1Wcuh2JpWLR1whmrvFFox4+yuAiB+8ESzFbL/F7znPtfMld9TCoh6Lzle
        LX21kfClCSdk5g==
        -----END CERTIFICATE-----
      KONG_CLUSTER_CERT_KEY: |
        -----BEGIN PRIVATE KEY-----
        MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgtOn4/Hs25WITVqf8
        +fxra1Djh4EMIMWVm71Mz3PhuJ2gCgYIKoZIzj0DAQehRANCAASUniPCX0oTI7oh
        DLa9fppfhKIs9a3iISfQWA8MzNkJr633VaTElpXjkQfufpzfmF/L3Wyc4Sdhm8Fl
        AYilrvTK
        -----END PRIVATE KEY-----
      KONG_LUA_SSL_TRUSTED_CERTIFICATE: system
      KONG_KONNECT_MODE: on
      KONG_CLUSTER_DP_LABELS: type:docker-macOsArmOS
      KONG_ROUTER_FLAVOR: expressions
    depends_on:
      - flights.kongair
      - routes.kongair
      - bookings.kongair
      - customer.kongair
      - experience.kongair
    ports:
      - "9000:9000"
      - "9443:9443"
