#!/bin/bash
docker run -d --name kong-air-dp \
-e "KONG_ROLE=data_plane" \
-e "KONG_DATABASE=off" \
-e "KONG_VITALS=off" \
-e "KONG_CLUSTER_MTLS=pki" \
-e "KONG_PROXY_LISTEN=0.0.0.0:9000, 0.0.0.0:9443 ssl" \
-e "KONG_CLUSTER_CONTROL_PLANE=77f85689e2.eu.cp.konghq.com:443" \
-e "KONG_CLUSTER_SERVER_NAME=77f85689e2.eu.cp.konghq.com" \
-e "KONG_CLUSTER_TELEMETRY_ENDPOINT=77f85689e2.eu.tp.konghq.com:443" \
-e "KONG_CLUSTER_TELEMETRY_SERVER_NAME=77f85689e2.eu.tp.konghq.com" \
-e "KONG_CLUSTER_CERT=-----BEGIN CERTIFICATE-----
MIICFjCCAbygAwIBAgIBATAKBggqhkjOPQQDBDA8MTowCQYDVQQGEwJFVTAtBgNV
BAMeJgBrAG8AbgBuAGUAYwB0AC0ASwBvAG4AZwBBAGkAcgAtAFAAUgBEMB4XDTI1
MTAwMjA4MDA0N1oXDTM1MTAwMjA4MDA0N1owPDE6MAkGA1UEBhMCRVUwLQYDVQQD
HiYAawBvAG4AbgBlAGMAdAAtAEsAbwBuAGcAQQBpAHIALQBQAFIARDBZMBMGByqG
SM49AgEGCCqGSM49AwEHA0IABJSeI8JfShMjuiEMtr1+ml+Eoiz1reIhJ9BYDwzM
2QmvrfdVpMSWleORB+5+nN+YX8vdbJzhJ2GbwWUBiKWu9Mqjga4wgaswDAYDVR0T
AQH/BAIwADALBgNVHQ8EBAMCAAYwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUF
BwMCMBcGCSsGAQQBgjcUAgQKDAhjZXJ0VHlwZTAjBgkrBgEEAYI3FQIEFgQUAQEB
AQEBAQEBAQEBAQEBAQEBAQEwHAYJKwYBBAGCNxUHBA8wDQYFKQEBAQECAQoCARQw
EwYJKwYBBAGCNxUBBAYCBAAUAAowCgYIKoZIzj0EAwQDSAAwRQIhAPP4NAH4gA3+
KqzhQgY1Wcuh2JpWLR1whmrvFFox4+yuAiB+8ESzFbL/F7znPtfMld9TCoh6Lzle
LX21kfClCSdk5g==
-----END CERTIFICATE-----" \
-e "KONG_CLUSTER_CERT_KEY=-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgtOn4/Hs25WITVqf8
+fxra1Djh4EMIMWVm71Mz3PhuJ2gCgYIKoZIzj0DAQehRANCAASUniPCX0oTI7oh
DLa9fppfhKIs9a3iISfQWA8MzNkJr633VaTElpXjkQfufpzfmF/L3Wyc4Sdhm8Fl
AYilrvTK
-----END PRIVATE KEY-----" \
-e "KONG_LUA_SSL_TRUSTED_CERTIFICATE=system" \
-e "KONG_KONNECT_MODE=on" \
-e "KONG_CLUSTER_DP_LABELS=type:docker-macOsArmOS" \
-e "KONG_ROUTER_FLAVOR=expressions" \
-p 9000:9000 \
-p 9443:9443 \
kong/kong-gateway:3.11